### ISSUE TITLE
doesn't work with Promise::AsyncAwait

### ISSUE THREAD

**Issue by rmesser** [FGasper/p5-Promise-XS#6]
Nice promises implementation. I'd like to use it with the async/awaits syntax, and the docs say:
> This module is Promise::AsyncAwait-compatible.

However that seems to no longer be true. A very simple test using 'await' fails. Here's the test:
```
use strict;
use warnings;

use Test::More;

use Promise::AsyncAwait;
 
async sub do_stuff { return 'test' }

my $test = await do_stuff();
is($test, 'test', "await async function that isn't really async");

done_testing;
```
The error message is `Can't locate object method "AWAIT_WAIT" via package "Promise::XS::Promise" at test1.pl line 10.`

The same test will work if "Future::AsyncAwait" is used instead of "Promise::AsyncAwait". It would be nice to use Promise::XS instead though, since it is more compatible with promises in other languages and apparently faster to boot. Thanks.

**Comment by FGasper** [comment]
@rmesser Thanks. Yeah it looks like a method got added to Future::AsyncAwait::Awaitable.

**Comment by FGasper** [comment]
I believe this is resolved.
